### ISSUE TITLE
Implement Database Purge

### ISSUE THREAD

**Issue by lgrosales** [danielwertheim/mycouch#126]
Is db/_purge implemented?

If not, do you accept PRs?

Cheers!
Leo

**Comment by danielwertheim** [comment]
Yes, PRs are accepted and welcomed.

On 21 Jun 2017 14:27, "Leonardo Rosales" <notifications@github.com> wrote:

Is db/_purge implemented?

If not, do you accept PRs?

Cheers!
Leo

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/danielwertheim/mycouch/issues/126>, or mute the thread

**Comment by lgrosales** [comment]
Good! There are a couple of endpoints I might need to add, but to begin with I was thinking to implement 
GET /{db}/_all_docs

Do you prefer me to do it under Documents or under Database?

**Comment by danielwertheim** [comment]
I think that should be under Documents

**Comment by danielwertheim** [comment]
Actually, this already exists. Via Views. The QueryViewRequest can take a SystemViewIdentity which as one for AllDocs

https://github.com/danielwertheim/mycouch/blob/69bedb65470097dd2b8f1b79f7bd7af695568c44/source/projects/MyCouch/Requests/QueryViewRequest.cs#L230

**Comment by lgrosales** [comment]
Purge is actually not implemented in CouchDB 2.0

https://groups.google.com/forum/#!topic/couchdb-user-archive/yDf965WCTMQ

**Comment by danielwertheim** [comment]
Should we keep this issue or close and implement if they get it implemented eventually? I'm for closing.

**Comment by lgrosales** [comment]
Close it.

Let me know if you need help with any other feature.
