### ISSUE TITLE
reading _design/selects

### ISSUE THREAD

**Issue by MadlFerenc** [danielwertheim/mycouch#201]
How can i read the document _design/selects as admin user from an c# application?
I got always the result: IsSucces=false
tried with MyCouchClient and MyCouchStore, without success
Can you help me ?

**Comment by danielwertheim** [comment]
Do you have any code showing what you are doing?

There are integration tests that accesses views that shows how it can be used: https://github.com/danielwertheim/mycouch/blob/master/source/tests/IntegrationTests/CoreTests/ViewsTests.cs

The views are defined here: https://github.com/danielwertheim/mycouch/blob/master/source/tests/Testing/TestData/ClientTestData.cs#L137

**Comment by MadlFerenc** [comment]
![couch_design_select](https://user-images.githubusercontent.com/63643731/111600030-432efe80-87d1-11eb-90c7-9e7f3b8be8c3.png)
no error, no reason, but exception.
query is working from Postman or curl with the same auth:
$ curl -X GET https://unstable:wcT9LgsNFrX3vJZ8NTyHBSE6M@movit-unstable.oebb.at/api/suv/couchdb/v1/sv-dev/_design/selects
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3760  100  3760    0     0  78333      0 --:--:-- --:--:-- --:--:-- 80000{"_id":"_design/selects","_rev":"77-22053e21b551ca159bb79a7d0a41a0c1","filters":{"getWeldings":"function(doc, req) { return  !doc._deleted && doc.user !== undefined && new Date(doc.creationDate) >= new Date(new Date().setFullYe

**Comment by danielwertheim** [comment]
Could it be something with redirects? If you debug and add the status you get here https://github.com/danielwertheim/mycouch/blob/master/source/projects/MyCouch/Net/Connection.cs#L152

Old issue with redirects https://github.com/danielwertheim/mycouch/issues/75

**Comment by MadlFerenc** [comment]
yes, authentication is enabled on the database.
you made some improvments according to #75 in 2015.
can i do something to resolve my issue?

**Comment by MadlFerenc** [comment]
sorry, i closed it unfortunately

**Comment by danielwertheim** [comment]
Can you debug and check the line were I pointed at (`ShouldFollowResponse`) and see if it works if you add the status you get `HttpStatusCode.Found` next to `HttpStatusCode.MovedPermanently` so that both statuses are allowed to determine if a Follow should happen. If, then a fix can be put out.

**Comment by MadlFerenc** [comment]
Hi Daniel, the problem is before.
Same as issue #75 with _design%2Fselects
i changed httpRequest/RelativeUrl from _design%2Fselects to _design/selects --> works
![couch_design_select_problem](https://user-images.githubusercontent.com/63643731/111651095-37a9fa80-8806-11eb-9b07-7d0f8a245c99.png)

**Comment by danielwertheim** [comment]
If I remember it correctly, the fix was based on the fact that the response of the 301 should contain the location on where to find the resource and instead of auto following, a new request was made. 302 could also carry the location to use instead. But the code doesn't handle 302 in the connection class. If you look at the 302 responses header here: https://github.com/danielwertheim/mycouch/blob/master/source/projects/MyCouch/Net/Connection.cs#L93

Does it then contain the proper URL in response.Headers.Location?

**Comment by MadlFerenc** [comment]
response.Headers.Location is not correct, a part of path is missing:
response.Headers.Location={http://movit-unstable.oebb.at/sv-dev/_design/selects}
![couch_design_select_header_location](https://user-images.githubusercontent.com/63643731/111805628-7c4e9800-88d1-11eb-892a-86d0dceb32cb.png)

should be: {https://movit-unstable.oebb.at/api/suv/couchdb/v1/sv-dev/_design/selects}
so after followMessage.RequestUri = response.Headers.Location; the new RequestUri isn't correct[](url)

**Comment by danielwertheim** [comment]
Not sure why your infrastructure doesn't give the "correct" values. Verified that the intentional behavior works in this commit: https://github.com/danielwertheim/mycouch/commit/bc7fb182da90c9c524a376c5e36edcba6e39b696

How-ever, there's another commit in that branch, that changes the behavior so that it should work for your environment as well. If you could verify that, then I can put out a new release.

**Comment by MadlFerenc** [comment]
with the changes in GenerateRequestUri() the result is also correct in my infrastructure, Thanks.

**Comment by danielwertheim** [comment]
Released in 7.5.1
