### ISSUE TITLE
View Returning Muliple Doc Types Question

### ISSUE THREAD

**Issue by mpaul31** [danielwertheim/mycouch#70]
i'm still new to couchdb so please bear with me. i am seeing examples of views where it is able to spit out multiple document types. for example, a customer can have one or more orders(two docs types) and the view can uses some ordering and emits to return a customer and all its orders, followed by the next customer and all its orders, etc.

is this supported in mycouch/cloudant (i am using entities)?

**Comment by danielwertheim** [comment]
Please provide sample models. But if you are using the entities  then what you get is essentially help with the deserializing of the returned JSON, and you will be bound to the contract of the defined entity, unless to e.g. `Dictionary<string, object>` or `dynamic` since it is using JSON.Net by Newtonsoft.
