### ISSUE TITLE
create views view documents does not work

### ISSUE THREAD

**Issue by egarim** [danielwertheim/mycouch#71]
Hi, I'm trying to create a view but the sample code does not seems to work any more

this is the view/docuement
{
    "_id": "_design/artists",
    "language": "javascript",
    "views": {
        "albums": {
            "map": "function(doc) {  if(doc.$doctype !== 'artist') return;  emit(doc.name, doc.albums);}" 
        }
    }
};
//the post method does not exist in the client I'm trying with PostAsync
client.Documents.Post(designDocumentAsJson);

the DocumentHeaderResponse rev and id are always null after run the code from above

**Comment by danielwertheim** [comment]
Don't forget to await the PostAsync call.

**Comment by egarim** [comment]
this is my code
   public async Task<DocumentHeaderResponse> CreateView()
        {
            string ViewText=System.IO.File.ReadAllText("test.txt");
            var Result = await this.Client.Documents.PostAsync(ViewText);
            return Result;
        }

where test.txt is this json

{
    "_id": "_design/Users",
    "language": "javascript",
    "views": {
        "Uniq": {
            "map": "function(doc) {  if(doc.pointer.type !== 'User') return;  emit(doc.userName, doc);}" 
        }
    }
    
};

**Comment by danielwertheim** [comment]
I'm not sure what sample code you were looking at.

Have you tried creating and accessing the view using e.g. curl or Postman?

Are you also waiting for the `CreateView` call?

When trying to access the view, note that it will be case sensitive.

**Working:** `GET http://localhost:5984/foo/_design/Users/_view/Uniq`

**Not working:** `GET http://localhost:5984/foo/_design/users/_view/Uniq`

**Also not working:** `GET http://localhost:5984/foo/_design/Users/_view/uniq`

Also not, what you probably are trying to do, will not work. Sure you will get the usernames, but they are by no means unique, since view results in CouchDB can be stale. And if using a distributed version of CouchDB as Cloudant or the upcoming version of CouchDB, it will be eventual consistent. In short, the only unique value of CouchDB is `_id`.

**Working PUT version**. Did `PutAsync` instead of `PostAsync`. But I also tried `PostAsync`.

```csharp
private async static Task CreateView()
{
    using (var client = new MyCouchClient("http://localhost:5984/foo"))
    {
        var head = await client.Documents.HeadAsync("_design/tickets");
        if (head.IsSuccess)
            return;

        var designdoc = File.ReadAllText("design_tickets.txt");
        var r = await client.Documents.PutAsync("_design/tickets", designdoc);
    }
}
```

where the view is something simple like:

```
{
   "language": "javascript",
   "views": {
       "bonusprogrammes": {
           "map": "function(doc) {\n  if(doc.$doctype !== 'ticket')\n    return;\n\n  emit(doc.traveller.bonusProgrammeId, null);\n}"
       }
   }
}
```

**Working Post version**.

```csharp
private async static Task CreateView()
{
    using (var client = new MyCouchClient("http://localhost:5984/foo"))
    {
        var head = await client.Documents.HeadAsync("_design/tickets");
        if (head.IsSuccess)
            return;

        var designdoc = File.ReadAllText("design_tickets.txt");
        var r = await client.Documents.PostAsync(designdoc);
    }
}
```

view

```
   "_id": "_design/tickets",
   "language": "javascript",
   "views": {
       "bonusprogrammes": {
           "map": "function(doc) {\n  if(doc.$doctype !== 'ticket')\n    return;\n\n  emit(doc.traveller.bonusProgrammeId, null);\n}"
       }
   }
}
```
