### ISSUE TITLE
Strong name 

### ISSUE THREAD

**Issue by endikamontejo** [danielwertheim/mycouch#72]
Good morning.
I would like to ask you if you have any intention to add an strong name to the package, in order developers can sign their projects automatically.
Regards,

Endika

**Comment by danielwertheim** [comment]
No intentions of providing that. As of now, you need to fork the repo and compile it with a strong name key file.

**Comment by endikamontejo** [comment]
ok, thanks for the response ;)

**Comment by adcorduneanu** [comment]
Hello guys, as you know most applications in .net need to be strongly named, and your library is not compliant with this. Please take into reconsideration this as it might be a blocker for those who are going to use your library.

Forking and recompiling are nothing else than extra work that can be done central, once, instead of 100k places. 

Thank you 🥇
