### ISSUE TITLE
Trying to use with ASP.NET 5 Dnx

### ISSUE THREAD

**Issue by adriaanp** [danielwertheim/mycouch#90]
Does MyCouch work on Mono and Dnx?

Currently trying to get it to work but getting issues with Ensure.That dependency that is at version 2.0.0. Dnx saying it is incompatible.

Any chance of updating reference to latest Ensure.That?

**Comment by danielwertheim** [comment]
You are more than welcome to try the `develop` branch version. Pull and compile and use the assembly that is a result of this project: https://github.com/danielwertheim/mycouch/tree/develop/source/projects/MyCouch.vNext

In that version, `Ensure.That` is also not a dependency any more, but instead included as source.

Let me know how it goes.

**Comment by adriaanp** [comment]
Will do, just need to figure out how to reference an assembly in the new project system :tongue:

**Comment by adriaanp** [comment]
There any change we can create a pre-release nuget package for development branch?

**Comment by danielwertheim** [comment]
Yes. Will do. But catching some Zzzzzzz now.

**Comment by adriaanp** [comment]
Any progress on this? Is there something I can do to get it published?

**Comment by danielwertheim** [comment]
Haven't had much time. But if you can get the vNext PCL working by making a local nuget and using that...

I'm also thinking of moving away from the PCL and instead have specific projects. E.g class lib for vnext.... Which will take me more time right now.

**Comment by adriaanp** [comment]
I have tried a few things with source code, but trying all this on my Mac and not using Visual Studio. So for now I don't care about a Core CRL version just a version that does not depend on Ensure.That 2.0.0

The current package would also work with Mono if the dll names did not changed in Ensure.That 3.2.0

**Comment by danielwertheim** [comment]
https://www.nuget.org/packages/MyCouch/4.0.0-rc1

No dependency on Ensure.That is it's included as source.

The package uses the .Net4.5 DLL for .Net4.5.x and .Net4.6 and currently the PCL for others. I have used that with a `dnxcore`, both as console and ASP.Net 5. But as I said. The PCL will be replaced. But for now, you should be able to use that.

In case you want to try/change/fix things and then test with a custom NuGet feed, you should be able to just run the PSake script under `deploy` (probably do a `nuget install` in the `deploy\tools` folder first, since I currently don't have that as part of the build script) and it will create NuGet packages for you.

**Comment by danielwertheim** [comment]
@adriaanp any luck with the rc-1?

**Comment by adriaanp** [comment]
Daniel works perfectly.

Thanks! :+1:

**Comment by danielwertheim** [comment]
Curious. Which environment did you run it in?

**Comment by adriaanp** [comment]
I'm running on Mac with Mono 4.0.4 and ASP.NET 5

**Comment by danielwertheim** [comment]
Closed, released with v4.0.0-rc1
